### ISSUE TITLE
document / check maximum block size

### ISSUE THREAD

**Issue by rroohhh** [szcompressor/SZ3#12]
afaict there are some (dimension dependent) limits on `SZ::Config::blockSize`
(for example here https://github.com/szcompressor/SZ3/blob/5736a63b917e439dd62248b4ff6234e96726af5d/include/SZ3/predictor/PolyRegressionPredictor.hpp#L189)
Currently this is not document anywhere (or I could not find any documentation) and also not checked.
So for example choosing a blockSize of `32` for a 3d input leads to memory corruption and a segfault down the line.

Let me know if you need a reproducer for this.

**Comment by ayzk** [comment]
Thank you very much for opening those issues. I've fixed them. For this one, the COEF_AUX_MAX_BLOCK is related to the auxiliary data in "PolyRegressionCoeffAux.hpp". It has nothing to do with the SZ::Config::blockSize. The explanation has been added.  If you experience segfault when changing SZ::Config::blockSize to 32, please share a reproducer with me.

**Comment by rroohhh** [comment]
Alright the following config (in file `sz.config`)
```
[GlobalSettings]
CmprAlgo = ALGO_LORENZO_REG
ErrorBoundMode = NORM
AbsErrorBound = 0.01
RelErrorBound = 0.00001
PSNRErrorBound = 70
L2NormErrorBound = 20
OpenMP = NO

[AlgoSettings]
InterpolationAlgo = INTERP_ALGO_CUBIC
InterpolationDirection = 0
Lorenzo = No
Lorenzo2ndOrder = No
Regression = No
Regression2ndOrder = Yes
BlockSize = 32
QuantizationBinTotal = 65536
```
produces a segfault on commit 40ad15ea25291fd6821f11c00fca43410e6fecdd when used like this:
`./examples/sz3 -f -i sz3_test.blob -o test.dat.sz -3 64 64 64  -M ABS 0.1 -a  -c sz.config`

(you can find the input I used at https://f.coroot.de/sz3_test.blob but I am pretty sure this segfaults regardless of  the input file)

**Comment by rroohhh** [comment]
Thank you for responding so quickly to my issues. 

I am aware poly regression is not the primary predictor, but I was just testing a combination of various parameters to check if my rust bindings (https://github.com/apertus-open-source-cinema/sz3-rs) work as expected and thats where I encountered these problems.

**Comment by ayzk** [comment]
You are welcome. Are you testing SZ on film data? How does it perform? This is a very interesting application domain. Feel free to contact me by email (kzhao016@ucr.edu) if you need additional help.

**Comment by rroohhh** [comment]
Currently we are investigating usage for storing calibration data, for example averaged darkframes. For these doing error bounded lossy compression looks to be really useful, especially because we have good estimates for the error bounds we need from the averaging process. In this usecase SZ3 was performing the best among the ones I tested (`SZ{,auto}`, `MGARD`, `zfp`, `fpzip`).
