### ISSUE TITLE
PolyRegressionPredictor tries to create HuffmanEncoder with zero bins

### ISSUE THREAD

**Issue by rroohhh** [szcompressor/SZ3#13]
https://github.com/szcompressor/SZ3/blob/5736a63b917e439dd62248b4ff6234e96726af5d/include/SZ3/predictor/PolyRegressionPredictor.hpp#L132
does not check if `regression_coeff_quant_inds` is empty, causing a segfault in `HuffmanEncoder`.

**Comment by ayzk** [comment]
fixed.
