### ISSUE TITLE
Unstructured Data Support?

### ISSUE THREAD

**Issue by RS-Coop** [szcompressor/SZ3#16]
Is unstructured input data supported? If so, what are the appropriate CLI options for compressing an unstructured dataset.

**Comment by ayzk** [comment]
Currently, SZ3 can only compress unstructured data as 1D input.

**Comment by RS-Coop** [comment]
Ah I see. Can any of the other tools in this SZ ecosystem handle 3D unstructured data?

**Comment by ayzk** [comment]
Unfortunately, we don't have specific tools to handle 3D unstructured data right now.

**Comment by CsatiZoltan** [comment]
@ayzk Any update on this or plan to support unstructured data? OpenZL solves it with a [domain specific language](https://openzl.org/sddl/) and supporting custom parsers. The idea is to let the user specify the components that the unstructured data is made of.

**Comment by ayzk** [comment]
@CsatiZoltan SZ3 does not support unstructured data right now. Let me ask my collaborators.

@robertu94 @lxAltria @guoxiliu Does any of your team have open repo that support unstructured data compression? Thanks.
