### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by rroohhh** [szcompressor/SZ3#18]
The following config (in file `sz.config`)
```
[GlobalSettings]
CmprAlgo = ALGO_LORENZO_REG
ErrorBoundMode = ABS
AbsErrorBound = 0.01
RelErrorBound = 0.00001
PSNRErrorBound = 70
L2NormErrorBound = 20
OpenMP = YES

[AlgoSettings]
InterpolationAlgo = INTERP_ALGO_CUBIC
InterpolationDirection = 0
Lorenzo = Yes
Lorenzo2ndOrder = No
Regression = Yes
Regression2ndOrder = No
BlockSize = 2
QuantizationBinTotal = 2097152
```

produces a segfault on commit 469c1446e2620cb411dc25e543d1bb72f066c371 when used like this:
`./examples/sz3 -f -i test.blob -o test.dat.sz -3 64 64 64  -M ABS 0.01 -a  -c sz.config`

(if `OMP_NUM_THREADS` is atleast `2`)

You can find the input I used at https://f.coroot.de/sz3_test.blob.

It looks like the `size_est` of the `FastFrontend` 
https://github.com/szcompressor/SZ3/blob/469c1446e2620cb411dc25e543d1bb72f066c371/include/SZ3/frontend/SZFastFrontend.hpp#L158-L162
ignores that the indicator array is huffman encoded and ignores that the regression parameters 
https://github.com/szcompressor/SZ3/blob/469c1446e2620cb411dc25e543d1bb72f066c371/include/SZ3/frontend/SZFastFrontend.hpp#L80 
are huffman encoded aswell.

**Comment by ayzk** [comment]
You are correct about cause of this issue. It has been fixed.
