### ISSUE TITLE
Overflow in conversion

### ISSUE THREAD

**Issue by pgrete** [szcompressor/SZ3#20]
```
./src/SZ3/tools/H5Z-SZ3/src/H5Z_SZ3.cpp:19:27: warning: overflow in conversion from ‘double’ to ‘int’ changes value from ‘2.0000000000000001e+32’ to ‘2147483647’ [-Woverflow]
   19 | int MAX_CHUNK_SIZE = 2E32 - 1;
      | 
```

Is this defined like this on purpose?

**Comment by ayzk** [comment]
@123epsilon Could you answer this question?

**Comment by 123epsilon** [comment]
@pgrete I believe I fixed this warning in my own repo, but we merged the PR just before I did so. @ayzk if you'd like you can use the small changes from this commit: https://github.com/123epsilon/SZ3/commit/a66327089586a3cb28d861ccff42b79332771151

The above commit fixes that warning and another in the filter related to a macro definition.

**Comment by ayzk** [comment]
@123epsilon Could you create a pull request to update the master? Thanks.

**Comment by 123epsilon** [comment]
@ayzk I've created a new PR https://github.com/szcompressor/SZ3/pull/21 that should resolve this

**Comment by ayzk** [comment]
@123epsilon Thanks. PR merged.
