### ISSUE TITLE
Cross-compilation - unsigned long is not always 64 bits

### ISSUE THREAD

**Issue by wingman-jr-addon** [szcompressor/SZ3#3]
There is a method in `ByteUtils` with references from the `HuffmanEncoder` that look like it may be assuming that `unsigned long` is always 64 bit. When cross-compiling with e.g. `mingw-w64` for x64, this is not true so compilation produces warnings.

https://github.com/szcompressor/SZ3/blob/f5fc429fcdb548cca5a50b8d9c1b3bd372ae4505/include/SZ3/utils/ByteUtil.hpp#L268-L277

**Comment by ayzk** [comment]
Both #3 and #4 have been fixed, could you compile SZ3 again? Thanks.

**Comment by wingman-jr-addon** [comment]
Awesome! I found another small issue on `make install` but I'll file a different bug for that. Thanks so much.
