### ISSUE TITLE
errBoundMode 10 not support

### ISSUE THREAD

**Issue by qingyiyi** [szcompressor/SZ3#33]
I used sz's PW_REL mode compression before, but the effect was not very satisfactory, so I tried to see if it would have the desired effect under SZ3, but I changed the code of SZ3 based on the original code and reported an error: **errBoundMode 10 not support**.
May I ask what is the reason

**Comment by ayzk** [comment]
@qingyiyi PW_REL is not supported yet in SZ3. Our plan is to add the support by this summer.
