### ISSUE TITLE
Is multi-threading possible?

### ISSUE THREAD

**Issue by hguan6** [szcompressor/SZ3#39]
I am using SZ3 C++ API and found that it runs on a single thread. I wonder if SZ3 supports multi-threading since I didn't see such an option in the configuration file.

**Comment by ayzk** [comment]
@hguan6 Yes, you need to follow the two steps:
1. Make sure OpenMP is supported/added in your compilation environment. The CMake process of SZ3 will automatically compile the OpenMP code if OpenMP is supported.
2. Change "OpenMP = NO" to "OpenMP = YES" in the config and use the '-c' parameter to pass the config to the executable.
