### ISSUE TITLE
Windows Cross-Compilation Support

### ISSUE THREAD

**Issue by wingman-jr-addon** [szcompressor/SZ3#5]
Thanks for the recent work that made `mingw-w64` successfully cross-compile the code. Only one minor issue seems to remain: the `.exe` extension is appended to the `sz` executable, which fails on `make install`.
Perhaps this line should somehow account for the difference in the binary name?
https://github.com/szcompressor/SZ3/blob/13b25a58154acf0f19ff93ec4cfd253a4baa2615/test/CMakeLists.txt#L10

Manually editing the configured cmake output to append `.exe` then caused the install to complete without issue.

**Comment by ayzk** [comment]
I made an update to suppress CMake adding the suffix of '.exe' in Windows. Could you try it and let me know? Thanks.

**Comment by wingman-jr-addon** [comment]
Thanks @ayzk - I gave it a try, but for some reason the file is still named `test/sz.exe` in the build folder.
In general, if you remove the `.exe` extension though, I think Windows might not run and treat it like a normal executable. Windows tends to rely on the extension more heavily for these things as even e.g. `.exe` vs. `.com` will have subtle differences in operation.

Additionally, I saw the commit message indicated this was a fix for Win32 - this is actually a Win64 build as I believe Win32 had some other issues during compilation so I assumed it was likely not supported (and not a big deal).

I'm not sure there's much for logs, but here are a few snippets.
```
Scanning dependencies of target sz
[ 97%] Building CXX object test/CMakeFiles/sz.dir/sz.cpp.obj
[100%] Linking CXX executable sz
[100%] Built target sz
[ 94%] Built target zstd
[ 97%] Linking CXX executable sz
[100%] Built target sz
Install the project...
```
and
```
-- Installing: XXX/sz3/build/win/x64/../../../install/win/x64/include/zstd_errors.h
CMake Error at test/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "XXX/sz3/build/win/x64/test/sz": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:68 (include)


make: *** [Makefile:129: install] Error 1
```

Again, thanks for your work!

**Comment by wingman-jr-addon** [comment]
So unfortunately I learned the hard way that SZ 2 does _not_ work on Windows, see https://github.com/szcompressor/SZ/issues/58
I'm not sure how similar the code bases are, but if SZ 3 shares the same issues, it's maybe better to just close this issue out as one that won't get fixed.

**Comment by ayzk** [comment]
@wingman-jr-addon I made some changes for SZ3 and it can produce correct results on Windows.  
Steps:
1. Install MSYS2 and Cmake on windows. Make sure to install the Mingw-w64 gcc and g++ following the MSYS2 instructions.
3. Build the project by cmake .. -G "MinGW Makefiles" and mingw32-make
5. run the sz executable.

**Comment by ayzk** [comment]
@wingman-jr-addon Thank you very much for the instruction for WSL.
I've replaced clock_gettime with std::chrono.

**Comment by vasole** [comment]
@wingman-jr-addon

> My end goal, however, was to include this into a Visual Studio solution

Current master seems to properly generate a Visual Studio solution

mkdir build
cd build
cmake -G"Visual Studio 16 2019" (or the default detected should work)

**Comment by wingman-jr-addon** [comment]
Sorry for the lengthy delay in responding; I was able to return at last to this project.
I can confirm that your changes to `std::chrono` allowed me to get rid of `clock_gettime` @ayzk , and cross-compilation went off without a hitch! Thanks!
@vasole Thanks for the comment.

Think we should be good to close now.

**Comment by legendPerceptor** [comment]
> 2\. cmake .. -G "MinGW Makefiles"

I found it not working in Windows MSYS2 MinGW64 env, but it worked in the MSYS2 UCRT64 environment.

After installing the MSYS2, open the UCRT64 terminal. Install the compiler and cmake by the following commands.

```bash
pacman -S mingw-w64-ucrt-x86_64-gcc
pacman -S mingw-w64-ucrt-x86_64-cmake
```

And then it just worked without -G "MinGW".

Go into the sz3 folder and run
```
mkdir windows-build && cd windows-build
cmake ..
cmake --build . -j 18
```

The sz3.exe will be successfully built.
