### ISSUE TITLE
 Fortran Wrappers for SZ3

### ISSUE THREAD

**Issue by ofmla** [szcompressor/SZ3#54]
I have recently created Fortran wrappers for SZ3, aiming to extend its accessibility to users who primarily work in Fortran. These wrappers provide seamless integration with Fortran programs, allowing users to leverage the functionality of SZ3 within their Fortran projects. I've developed a simple CI workflow that tests the wrappers by running a pysz example and comparing the outputs with its Fortran counterpart to ensure consistency. While this isn't a formal issue, I wanted to notify you of this development and kindly request to include a link to the Fortran wrappers in the README of the official SZ3 repository. This would make it easier for users to discover and utilize these wrappers, thus improving the overall usability of SZ3.

Wrapper Link: https://github.com/ofmla/sz3_simple_example

If you require any further information or assistance regarding the wrappers or their integration, please don't hesitate to reach out. Thank you for considering this request, and I look forward to seeing the Fortran wrappers linked in the README.

Best regards,
Oscar

**Comment by ayzk** [comment]
@ofmla Oscar, thank you very much for providing this Fortran wrappers. I've added the link on the README page.

Best,
Kai
