### ISSUE TITLE
Missing compression data file

### ISSUE THREAD

**Issue by BitCalSaul** [szcompressor/SZ3#57]
Hi,

Thank you for your efforts in developing SZ3. I am trying to check the compressed data file, but I am unable to locate it in the directory suggested by SZ3.

Here is the command I used:

`sz3 -f -i /data/dark_matter_density.f32 -t /data/test.f32.sz -3 512 512 512 -M REL 5E-3 -a`
And here is the output:

```
compression ratio = 3997.16 
compression time = 1.901435
compressed data file = /data/dark_matter_density.f32.sz.tmp
Min=0, Max=13778.9345703125, range=13778.9345703125
Max absolute error = 69
Max relative error = 0.005
Max pw relative error = 2.2E+08
PSNR = 72.364382, NRMSE= 0.000240869003
normError = 38450.455977, normErr_norm = 0.378328
acEff=0.927803
compression ratio = 3997.162687
decompression time = 0.797161 seconds.
decompressed file = /data/test.f32.sz
```
However, I cannot find the compressed data file at /data/dark_matter_density.f32.sz.tmp. Could you please help me locate the file or provide any insights on why it might not be appearing?

Thank you!

**Comment by ayzk** [comment]
The output need to be specified by '-o file_path'.  If you want it in text, please add '-t' in addition to the '-o file_path'. So the correct command should be
sz3 -f -i /data/dark_matter_density.f32 -o /data/test.f32.txt -t -3 512 512 512 -M REL 5E-3 -a
Thanks.
