### ISSUE TITLE
Allocate sufficient compression buffer on demand

### ISSUE THREAD

**Issue by juntyr** [szcompressor/SZ3#71]
SZ3 is quite complex internally and so it's even more complex to allocate a buffer for compression output beforehand that's appropriately sized.

The current `char *SZ_compress` implementation just tries to allocate twice the input data size, which is sometimes insufficient (e.g. #70). It would be really useful for end users to have a method that will always allocate a sufficiently sized buffer (or alternatively a helper function that can pre-compute how large such a buffer would need to be). In some cases, it is otherwise impossible to provide an infallible (sort of) interface to SZ3, even when all the config parameters are pre-validated.

**Comment by ayzk** [comment]
Thanks for your pull request. 
I've added the function to get size bound based on your code:
https://github.com/szcompressor/SZ3/blob/07cee4b95feaead2e441c45cf241b21ae9feef68/include/SZ3/api/impl/SZImpl.hpp#L35
I've also added the logic to check for the buffer size in the compression API:
https://github.com/szcompressor/SZ3/blob/07cee4b95feaead2e441c45cf241b21ae9feef68/include/SZ3/api/sz.hpp#L58
https://github.com/szcompressor/SZ3/blob/07cee4b95feaead2e441c45cf241b21ae9feef68/include/SZ3/api/sz.hpp#L100

**Comment by juntyr** [comment]
Thanks! The new function works like a charm!
